version = 1
SPDX-PackageName = "XYO SDK Static Installer"
SPDX-PackageSupplier = "Grigore Stefan <g_stefan@yahoo.com>"
SPDX-PackageDownloadLocation = "https://github.com/g-stefan/installer-xyo-sdk"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = ".github/CODE_OF_CONDUCT.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 Coraline Ada Ehmke <https://where.coraline.codes/>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = ".clang-format"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = ".vscode/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = ".claude/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = "fabricare.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "source/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "source/xyo-sdk.license.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "LicenseRef-OpenSource"

[[annotations]]
path = "installer/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "LicenseRef-OpenSource"

[[annotations]]
path = "output/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "LicenseRef-OpenSource"

[[annotations]]
path = "release/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "LicenseRef-OpenSource"

[[annotations]]
path = "temp/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "LicenseRef-OpenSource"

[[annotations]]
path = "vendor/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "LicenseRef-OpenSource"
